
(function () {
  const config = window.MEDISPOT_SUPABASE || {};
  const configured = config.url && config.anonKey && !config.url.includes('YOUR_PROJECT_ID') && !config.anonKey.includes('YOUR_SUPABASE_ANON_KEY');
  const supabaseClient = configured && window.supabase ? window.supabase.createClient(config.url, config.anonKey) : null;
  const t = {
    nurse:'スポット看護師', clinic:'新宿メディカルクリニック', nurseCat:'看護師', spot:'スポット', tokyo:'東京都 新宿区', friday:'今週金曜 9:00-17:00', nursePay:'日給 18,000円〜22,000円', nurseDesc:'外来補助、採血、問診、処置準備を担当します。短時間勤務の相談も可能です。', nurseReq:'看護師免許、採血経験', lab:'臨床検査技師', labFacility:'横浜健診センター', contract:'業務委託', kanagawa:'神奈川県 横浜市', weekly:'週1日から相談', labPay:'日給 16,000円〜20,000円', labDesc:'健診における検体検査、生理検査、結果入力を担当します。', labReq:'臨床検査技師免許', radio:'放射線技師', radioFacility:'大阪画像診断クリニック', part:'パート', osaka:'大阪府 大阪市', saturday:'土曜午前', radioDesc:'一般撮影、CT補助、検査前後の患者案内を担当します。', radioReq:'診療放射線技師免許', match:'マッチ度高', medicalJob:'医療求人', facility:'医療機関', salaryAsk:'給与相談', detail:'詳細を見る', none:'条件に合う求人がありません。条件を変更して検索してください。', count:'件', detailTitle:'求人詳細', defaultDesc:'業務内容は医療機関と確認します。', applied:'応募済み', applyDone:'応募を受け付けました。応募管理ページへ移動します。', appJob:'応募求人', noApps:'まだ応募はありません。求人検索から応募できます。' };
  const demoJobs = [
    { id:'demo-nurse', title:t.nurse, facility_name:t.clinic, category:t.nurseCat, type:t.spot, location:t.tokyo, work_date:t.friday, salary:t.nursePay, description:t.nurseDesc, requirements:t.nurseReq, image:'assets/job-nurse.png' },
    { id:'demo-lab', title:t.lab, facility_name:t.labFacility, category:t.lab, type:t.contract, location:t.kanagawa, work_date:t.weekly, salary:t.labPay, description:t.labDesc, requirements:t.labReq, image:'assets/job-lab.png' },
    { id:'demo-radiology', title:t.radio, facility_name:t.radioFacility, category:t.radio, type:t.part, location:t.osaka, work_date:t.saturday, salary:t.labPay, description:t.radioDesc, requirements:t.radioReq, image:'assets/job-radiology.png' }
  ];
  function esc(v) { return String(v || '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])); }
  function getParam(name) { return new URLSearchParams(location.search).get(name); }
  function localApps() { try { return JSON.parse(localStorage.getItem('medispot_applications') || '[]'); } catch { return []; } }
  function saveLocalApp(app) { const apps = localApps(); apps.unshift(app); localStorage.setItem('medispot_applications', JSON.stringify(apps)); }
  function imageFor(job) { const c = String(job.category || ''); return job.image || (c.includes(t.lab) ? 'assets/job-lab.png' : c.includes(t.radio) ? 'assets/job-radiology.png' : 'assets/job-nurse.png'); }
  async function logoutWire() { const btn = document.getElementById('logoutButton'); if (!btn) return; btn.addEventListener('click', async () => { if (supabaseClient) await supabaseClient.auth.signOut(); location.href='login.html'; }); }
  function card(job) { return '<article class="job-card"><div class="job-thumb"><img src="'+esc(imageFor(job))+'" alt=""></div><div><span class="job-tag">'+esc(job.type || t.spot)+'</span><span class="job-tag match-tag">'+t.match+'</span><h3>'+esc(job.title || job.category || t.medicalJob)+'</h3><p class="job-meta">'+esc(job.facility_name || t.facility)+' / '+esc(job.location || '')+' / '+esc(job.work_date || '')+'</p><div class="job-salary">'+esc(job.salary || t.salaryAsk)+'</div></div><div class="job-actions"><a class="btn btn-outline" href="job-detail.html?id='+encodeURIComponent(job.id)+'">'+t.detail+'</a></div></article>'; }
  async function loadJobsPage() { const list = document.getElementById('jobsList'); if (!list) return; let jobs = demoJobs; if (supabaseClient) { const r = await supabaseClient.from('jobs').select('*').eq('status','open').order('created_at',{ascending:false}); if (!r.error && r.data && r.data.length) jobs = r.data; } const render = () => { const cat = document.getElementById('category').value; const loc = document.getElementById('location').value.trim(); const type = document.getElementById('type').value; const day = document.getElementById('workDate').value; const filtered = jobs.filter(j => (!cat || j.category === cat) && (!loc || String(j.location || '').includes(loc)) && (!type || j.type === type) && (!day || String(j.work_date || '').includes(day))); document.getElementById('jobCount').textContent = filtered.length + t.count; list.innerHTML = filtered.length ? filtered.map(card).join('') : '<div class="panel">'+t.none+'</div>'; }; document.getElementById('searchButton').addEventListener('click', render); render(); }
  async function findJob(id) { if (supabaseClient && id && !id.startsWith('demo-')) { const r = await supabaseClient.from('jobs').select('*').eq('id', id).maybeSingle(); if (!r.error && r.data) return r.data; } return demoJobs.find(j => j.id === id) || demoJobs[0]; }
  async function loadDetailPage() { const title = document.getElementById('jobTitle'); if (!title) return; const job = await findJob(getParam('id')); title.textContent = job.title || t.detailTitle; document.getElementById('jobLead').textContent = (job.facility_name || t.facility) + ' / ' + (job.location || ''); document.getElementById('jobType').textContent = job.type || t.spot; document.getElementById('jobSalary').textContent = job.salary || t.salaryAsk; document.getElementById('facility').textContent = job.facility_name || t.facility; document.getElementById('locationText').textContent = job.location || '-'; document.getElementById('workDateText').textContent = job.work_date || '-'; document.getElementById('requirements').textContent = job.requirements || job.category || '-'; document.getElementById('description').textContent = job.description || t.defaultDesc; document.getElementById('applyButton').addEventListener('click', async () => { const msg = document.getElementById('message'); const app = { job_id: job.id, job_title: job.title, facility_name: job.facility_name, status:t.applied, message: document.getElementById('applyMessage').value.trim(), created_at: new Date().toISOString() }; saveLocalApp(app); if (supabaseClient) { const session = await supabaseClient.auth.getSession(); const user = session.data.session?.user; if (user) await supabaseClient.from('seeker_applications').insert(Object.assign({}, app, { user_id:user.id })); } msg.style.display='block'; msg.textContent=t.applyDone; setTimeout(() => location.href='seeker-applications.html', 800); }); }
  async function loadApplicationsPage() { const list = document.getElementById('applicationsList'); if (!list) return; let apps = localApps(); if (supabaseClient) { const session = await supabaseClient.auth.getSession(); const user = session.data.session?.user; if (user) { const r = await supabaseClient.from('seeker_applications').select('*').eq('user_id', user.id).order('created_at',{ascending:false}); if (!r.error && r.data && r.data.length) apps = r.data; } } list.innerHTML = apps.length ? apps.map(a => '<article class="job-card"><div><span class="status">'+esc(a.status || t.applied)+'</span><h3>'+esc(a.job_title || t.appJob)+'</h3><p class="job-meta">'+esc(a.facility_name || t.facility)+' / '+esc((a.created_at || '').slice(0,10))+'</p></div><div class="job-actions"><a class="btn btn-outline" href="job-detail.html?id='+encodeURIComponent(a.job_id || '')+'">'+t.detail+'</a></div></article>').join('') : '<div class="panel">'+t.noApps+'</div>'; }
  logoutWire(); loadJobsPage(); loadDetailPage(); loadApplicationsPage();
})();
